version: '3.0'
services:

  nginx:
  
      image: nginx:latest
  
      ports:
  
        - 8088:80
  
      volumes:
  
        - ./nginx/conf/conf.d/:/etc/nginx/conf.d/

        - ./nginx/app:/app
  rasa:

    image: rasa/rasa:latest-full

    ports:

      - 5005:5005
    volumes:

      - ./:/app

    command:

      - run

  action_server:    

    build: 
        context: ./
        dockerfile: Dockerfile.actions

    volumes:     
      
      - ./actions:/app/actions
      - ./flight.db:/app/flight.db
    ports:
      - 5055:5055